name: project2
on:
  push:
    paths:
    - './project2/league.txt'
  status: {}
jobs:
  project2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ./project2/requirements.txt

      - name: run script
        run: python -m ./project2/parse $(cat ./project2/league.txt)
      
      - name: push results to repo
        run: |
          REMOTE=https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add .
          git commit -m "Add new comment"
          git push ${REMOTE}
